# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for MCP Notes
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy project files
COPY package.json tsconfig.json .
COPY src ./src
COPY prompts ./prompts
COPY search-utils.ts index.ts memory-bank ./

# Install dependencies and build
RUN npm install && npm run build

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built artifacts
COPY --from=builder /app/dist ./dist

# Copy production dependencies manifest
COPY package.json .

# Install production dependencies without running prepare or build scripts
RUN npm install --production --ignore-scripts

# Entrypoint (CLI stdio server)
ENTRYPOINT ["node", "dist/index.js"]
